# Asset Priority List 
Assets will be made according to need. If the software framework is done or almost done, I'll make the asset. 
If you add anything to my list, you better write what it's for and tell me if we have the feature completed. Let me know it's purpose and how it'll be used in the game. Also let me know how it moves and different states it will have. If you need to explain somethign complex or specific like a UI element, make me a sketch of what you're thinking.
## Pawns:
- main character holding a sword (one at full health and another at low health, has swinging animation & consuming animation)
- evil bug enemy (flaps it's wings when it flies & stings when it attacks)

## Settings:
- bedroom (starting scene) 

## Items:
- apple (able to hang on a tree & used in conjunction with healing)
- health potion (used in conjunction with healing)

## Objects:
- Treasure chest (one open and one closed)
- barrel (one whole and one in pieces)

## UI Elements:
- health bar frame (with transparent inside for the health bar generated by the backend)
